# Generated by Django 4.2 on 2023-05-22 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='picture',
            field=models.ImageField(blank=True, default='media/media/images/users/photo_2023-04-19_10-20-05.jpg', upload_to='media/images/users'),
        ),
    ]
