# Generated by Django 4.2 on 2023-05-13 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerdata',
            name='num',
        ),
        migrations.AddField(
            model_name='answerdata',
            name='username',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
