# Generated by Django 4.2 on 2023-05-13 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive', '0003_remove_answerdata_num_answerdata_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerdata',
            name='leader',
        ),
        migrations.AddField(
            model_name='answerdata',
            name='leader_name',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
