# Generated by Django 4.2 on 2023-05-13 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interactive', '0004_remove_answerdata_leader_answerdata_leader_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerdata',
            name='leader_name',
        ),
        migrations.AddField(
            model_name='answerdata',
            name='leader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='interactive.leader'),
        ),
    ]
