# Generated by Django 4.2 on 2023-05-22 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive', '0005_remove_answerdata_leader_name_answerdata_leader'),
    ]

    operations = [
        migrations.AddField(
            model_name='leader',
            name='content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leader',
            name='link',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
